### PR TITLE
Upgrade to Cake 3.6+

### PR DESCRIPTION
**Pull request by bravo-kernel**
I have made a start with preparing for the 3.6 release but am hitting some walls, committing anyway, help appreciated.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Stepping away for now as this has taken about 4 hours and I am still hitting crazy errors. Help appreciated.

**Comment by josegonzalez** [comment]
\o/

**Comment by bravo-kernel** [comment]
Does that mean we have your blessing to merge and release @josegonzalez ?

**Comment by josegonzalez** [comment]
What happened with JsonApiRoute?

**Comment by bravo-kernel** [comment]
I deleted it, it was my work in progress but was never finished and I forgot to remove it. It was intended to generate specific links.

I basically stopped when @ADmad told me the idea was silly.

**Comment by ADmad** [comment]
> I basically stopped when @ADmad told me the idea was silly.

Did I? I don't remember the related discussion. :)

**Pull request merged**
