### PR TITLE
Support routes without fallback (Set _method parameter in Router::normalize call)

### PR DESCRIPTION
**Pull request by chrisShick**
This is in relation to issue [#18](https://github.com/FriendsOfCake/crud-json-api/issues/18)

### CODE REVIEW

**Comment by chrisShick** [comment]
@ADmad This passed all php version 5.6 and above. I'm not sure why anything below 5.6 are included in the travis-ci.

**Comment by bravo-kernel** [comment]
Mr. Admad does not follow this repo. I will see if I can fix these failing tests this weekend (if you can’t figure it out). Unfortunately.... if Crud supports these old versions so should we

**Comment by chrisShick** [comment]
@bravo-kernel I already know the issue. I should have paid more attention that this supports Cakephp 3.0 and above. I am about to do a push now.

**Comment by ADmad** [comment]
> Mr. Admad does not follow this repo

That's what I thought too but I am still getting notifications for it. I should fix that :stuck_out_tongue:

**Comment by chrisShick** [comment]
@bravo-kernel That passed the travis-ci checks but it appears it doesn't pass the codecov/patch & project checks. Would this be because of there being not PaginationListenerTest case?

**Comment by bravo-kernel** [comment]
Correct, you should probably add a test for the untested parts, the codecov site can show you what is missing (the red parts)

**Comment by chrisShick** [comment]
@bravo-kernel is this a case in which we will need to add a PaginationListenerTest?? If so, I will try to do that now.

**Comment by bravo-kernel** [comment]
Almost there mr. @chrisShick, just some minor coding standard issues to fix. See https://travis-ci.org/FriendsOfCake/crud-json-api/jobs/294242471.

**Comment by bravo-kernel** [comment]
## New problem description based on PM conversation ##

The problem can be summarized as **pagination links are not generated**.

## Assistance needed 

As discussed I'm a bit reluctant to "just" merge this because:

- pagination links are generated just fine in both my test-app and the already existing tests. 
- I cannot reproduce the error
- I cannot see additional checks in the test you added (compared to the existing ones like [this](https://github.com/FriendsOfCake/crud-json-api/blob/64a89102899b5f1173b2b7985c8e37374d9da155/tests/TestCase/Integration/JsonApi/DefaultIndexActionIntegrationTest.php) and [this](https://github.com/FriendsOfCake/crud-json-api/blob/3c9179c0e7e86c7269d2411ceaee074e515eca2a/tests/TestCase/View/JsonApiViewTest.php#L574))

To be clear, I could very well be wrong and don't want to put you off but I think we have two options here:

- ask a @FriendsOfCake/json-api if your proposed change makes sense (I honestly can't tell)
- find a way for me to reproduce the error 

FWIW I was able to reproduce the error you started ticket #18 by using Postman to connect to an index page with pagination links, then clicking one of the pagination links. The error for that click made sense because Postman does not add the correct JSON API headers, hence the error.

## Working pagination (relative and absolute)

image

image

**Comment by chrisShick** [comment]
I have installed new 3 Cakephp projects, crud, and crud-json-api. I have used 3 different databases and 3 different types of resource names. The error occurs every time. It might be worth mentioning that the operating system in use is a MacOS - High Sierra.

**Comment by ADmad** [comment]
@chrisShick Can you provide some minimal code to help reproduce the error you are having?

**Comment by chrisShick** [comment]
@ADmad I have provided the code in the issue #18

**Comment by chrisShick** [comment]
I also just tested on a clean aws linux ami with php71 and it gives the same error as my mac does. Once I update the PaginationListener with my fix above, the error goes away.

**Comment by chrisShick** [comment]
I am attaching the zip of the html directory on a linux ami using cakephp 3.4.4 and all the updated crud and crud json api. I have also tested with the latest version of cakephp 3.5.5 with no difference. Both cakephp versions give the error. I am now curious how @bravo-kernel is not able to replicate it.
[html.tar.gz](https://github.com/FriendsOfCake/crud-json-api/files/1443500/html.tar.gz)

**Comment by bravo-kernel** [comment]
@chrisShick I just created a working copy using the blog repository sources like so:

```bash
git clone https://github.com/bravo-kernel/application-examples.git
cd application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi
composer install

# set database + credentials in your app.php
bin/cake migrations migrate

# point your vhost webroot to `/application-examples/blog-how-to-make-your-cakephp-3-api-produce-jsonapi/webroot`
```

image

**Comment by bravo-kernel** [comment]
I still only see one difference with your [initial ticket](https://github.com/FriendsOfCake/crud-json-api/issues/18#issue-268976513), you are using a prefix (`v1`) inside a prefix (`api`)
 
> http://localhost:8765/api/v1/customers

**Comment by bravo-kernel** [comment]
## Reproducable

And... I can now reproduce the error by creating the same `routes` setup you have for the multi-nested prefix:

```php
Router::prefix('api', function ($routes) {
    $routes->extensions(['json', 'xml']);
    $routes->resources('Cocktails');
    $routes->resources('Users');

    $routes->prefix('v1', function ($routes) {
        $routes->resources('Cocktails', [
            'inflect' => 'dasherize'
        ]);
    });
```

image

**Comment by bravo-kernel** [comment]
Good find mr. @chrisShick, I think it would be nice if the added test would actually assert a multi-nested prefix (failing without your fix) but I am now convinced, thanks 💓

**Comment by bravo-kernel** [comment]
## Works for me

After adding fallback routes to the `routes.php` file like shown below, `/api/v1/customers` now generates the correct result (incuding the correct multi-prefix pagination links).

```php
Router::prefix('api', function ($routes) {
    $routes->extensions(['json', 'xml']);
    $routes->resources('Customers');

    $routes->prefix('v1', function ($routes) {
        $routes->resources('Customers', [
            'inflect' => 'dasherize'
        ]);
        $routes->fallbacks('InflectedRoute');
    });

    $routes->fallbacks('InflectedRoute');
});
```

image

**Comment by bravo-kernel** [comment]
## Better

The fix by mr. @chrisShick makes things even better, we can now route like this:

```php
Router::prefix('api', function ($routes) {
    $routes->extensions(['json', 'xml']);
    $routes->resources('Cocktails');

    $routes->prefix('v1', function ($routes) {
        $routes->resources('Cocktails', [
            'inflect' => 'dasherize'
        ]);
    });
});
```

**Comment by bravo-kernel** [comment]
Closing as this was fixed in https://github.com/FriendsOfCake/crud-json-api/commit/a70b15a3bf3d0ba209554ad0b7ed215406254caf

**Comment by chrisShick** [comment]
It appears this fix did not get applied to the 4.x release of this plugin. Should I make another pull request for that branch?

**Pull request closed without merging**
