### PR TITLE
Remove _joinData property, if use belongsToMany

### PR DESCRIPTION
**Pull request by josindraa**

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Please fix the CS. @dakota could you review/approve?

**Comment by josindraa** [comment]
Error does not appear to be DynamicEntitySchema.php but at JsonApiListener.php.

**Comment by bravo-kernel** [comment]
I see and you are correct. Nevertheless, would you mind adding the fix so the button goes green? 

FYI I cannot judge the impact but if this gets approved I will merge straight in and release.

**Comment by bravo-kernel** [comment]
@josindraa thank you kindly 👍

**Review by dakota — APPROVED** [review]

**Pull request merged**
